AWSTemplateFormatVersion: '2010-09-09'
Description: "Deploy de uma função Lambda simples usando CloudFormation"

Resources:
# Role que permite a Lambda acessar o S3 e escrever logs no CloudWatch
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MinhaRoleLambda
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - lambda.amazonaws.com
            Action: 
              - sts:AssumeRole
      Policies:
        - PolicyName: LambdaS3AccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: "arn:aws:s3:::my-lambda-jk/*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:DescribeTable
                  - dynamodb:UpdateItem 
                  - dynamodb:DeleteItem 
                Resource: "*"
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:GetParametersByPath
                Resource: "arn:aws:ssm:us-east-1:381645837582:parameter/BooksTable" 

  # Tabela DynamoDB para livros
  LivroTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "BooksTable"
      AttributeDefinitions:
        - AttributeName: "Id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "Id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  

  # Função Lambda
  MinhaFuncaoLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: minha-funcao-lambda
      Runtime: dotnet8
      Handler: BookServiceLambda::BookService.Functions.BookHandler::Handler
      Code:
        S3Bucket: my-lambda-jk
        S3Key: minha-lambda.zip
      Role: !GetAtt LambdaExecutionRole.Arn
      MemorySize: 512
      Timeout: 10

Outputs:
  MinhaFuncaoLambdaArn:
    Description: "ARN da Função Lambda"
    Value: !GetAtt MinhaFuncaoLambda.Arn
    Export:
      Name: MinhaFuncaoLambdaArn  # Nome do export para importar depois

  MinhaRoleLambda:
    Description: "ARN da Role Lambda"
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: MinhaRoleLambda